feat(index): add updates array & update field
FOLHOMEE/mongoose-tracker pull request #1
Opened 2022-01-14 08:37 UTC by barder60

La fonction mongooseTracker permet dans le cas d'une modification sur une listes de champs indiqué sa modification dans l'object lui meme.

On peut renommer le tableau via l'option name dans le plugin et transmettre la listes de champs a tracker dans l'option fieldsToTrack.

asana : https://app.asana.com/0/1182821898187524/1199674762347981

2022-01-14 09:00 UTC, milanito requested changes
Pas mal de remarques

2022-01-14 09:00 UTC, milanito commented on package.json
> +    "mongoose": "^6.1.5"
Non mongoose doit être dans les peer dependencies (ca y était d'ailleurs)

2022-01-14 09:00 UTC, milanito commented on package.json
> +    "mongodb-memory-server": "^8.1.0",
Non c'est une dev dep

2022-01-14 09:00 UTC, milanito commented on package.json
> +    "moment": "^2.29.1",
Ca devrait être dans les dependencies, et il faudrait utiliser [luxon](https://moment.github.io/luxon/#/) plutot => https://momentjs.com/docs/

2022-01-14 09:00 UTC, milanito commented on src/index.ts
> +          at: moment().toDate()
Tu as pas besoin de `moment` ni de `luxon` en fait, il suffit de faire `Date.now()`, ca t'enleve une dépendence

2022-01-14 09:00 UTC, milanito commented on src/index.ts
> +    if (updatedFields == null) {
`isNull` tu utilises lodash

2022-01-14 09:00 UTC, milanito commented on src/index.ts
> +    for (const [key, value] of Object.entries(updatedFields)) {
`toPair` de lodash

2022-01-14 09:00 UTC, milanito commented on src/index.ts
> +              at: moment().toDate()
`Date.now()`

2022-01-14 09:00 UTC, milanito commented on src/index.ts
> +        void this.update({}, {
il faut faire un `this.set` plutot que de faire un `this.update` à chaque fois non ? Et construit le tableau directement avec un `reduce` et fait le `set` à la fin

2022-01-14 09:00 UTC, milanito commented on src/index.ts
> +        void this.update({}, {
Il faudra faire

```
[name]: {
  $push: {
    $each: array
  }
}
```

2022-01-14 09:00 UTC, milanito commented on test/index.test.ts
> +  describe('name system', () => {
saute une ligne

2022-01-14 09:00 UTC, milanito commented on test/index.test.ts
> +    }
le delete devrait etre fait entre chaque tests

2022-01-14 09:07 UTC, barder60 commented on test/index.test.ts
> +  describe('name system', () => {
:+1:

2022-01-14 09:09 UTC, barder60 commented on test/index.test.ts
> +    }
:+1:

2022-01-14 09:10 UTC, barder60 commented on src/index.ts
> +              at: moment().toDate()
:+1:

2022-01-14 09:11 UTC, barder60 commented on src/index.ts
> +    if (updatedFields == null) {
:+1:

2022-01-14 09:11 UTC, barder60 commented on src/index.ts
> +          at: moment().toDate()
:+1:

2022-01-14 09:12 UTC, barder60 commented on package.json
> +    "moment": "^2.29.1",
du coup je l'ai retiré :+1:

2022-01-14 09:13 UTC, barder60 commented on package.json
> +    "mongoose": "^6.1.5"
:+1:

2022-01-14 09:13 UTC, barder60 commented on package.json
> +    "mongodb-memory-server": "^8.1.0",
:+1:

2022-01-14 10:51 UTC, barder60 commented on src/index.ts
> +    for (const [key, value] of Object.entries(updatedFields)) {
:+1:

2022-01-24 16:14 UTC, barder60 commented on src/index.ts
> +        void this.update({}, {
:+1:  du coup ça m'a pris du temps mais on peut set comme ceci dans l'update : 
```
void this.set({
      [name]: [...oldTrackedFields, ...trackedFields]
 })
```

2022-01-25 09:42 UTC, jeagdb commented on src/index.ts
> +    void this.set({
le void permet quoi ?

2022-01-25 13:51 UTC, barder60 commented on src/index.ts
> +    void this.set({
Enfaite le linter me renvoyait ceci 
![image](https://user-images.githubusercontent.com/35100599/150989147-edeb0436-af50-48a3-90fd-8cf3a949a870.png)
Le void permet de ne pas gérer le cas où le set c'est mal passé

2022-01-25 13:52 UTC, barder60 commented on src/index.ts
> +    void this.set({
Je peux mettre un catch avec un console.log :+1: 
```
this.set({
      [name]: [...oldTrackedFields, ...trackedFields]
    }).catch((err) => console.log(err))
```

2022-01-25 17:31 UTC, milanito reviewed
Il faudrait que tu revois les sauts de lignes entre les `it` et surtout les phrases en anglais qui décrivent les tests parce que c'est pas hyper clair niveau grammaire/orthographe 😄

2022-01-25 17:31 UTC, milanito commented on package.json
> +    "mongodb-memory-server": "^8.1.0",
non tu en as pas besoin dans les peer deps c'est un dev dep, https://nodejs.org/es/blog/npm/peer-dependencies/  https://medium.com/@stalonadsl948/dependencies-vs-devdependencies-926e096a3dee

2022-01-25 17:31 UTC, milanito commented on src/index.ts
> +}
Fait plutot un fichier de type à part

2022-01-25 17:31 UTC, milanito commented on src/index.ts
> +  fieldsToTrack: [string]
c'est plutot `string[]` ou `Array<string>` ta notation n'est pas un type

2022-01-25 17:31 UTC, milanito commented on test/index.test.ts
> +  describe('name system', () => {
Le describe ne veut rien dire

2022-01-26 08:41 UTC, barder60 commented on src/index.ts
> +}
:+1:

2022-01-26 09:24 UTC, barder60 commented on package.json
> +    "mongodb-memory-server": "^8.1.0",
:+1:

2022-01-26 09:24 UTC, barder60 commented on src/index.ts
> +  fieldsToTrack: [string]
:+1:

2022-01-26 14:11 UTC, barder60 commented on test/index.test.ts
> +  describe('name system', () => {
J'ai changé le nom pour tracker array key name

2022-01-27 13:19 UTC, milanito approved these changes
👍

2022-01-27 13:50 UTC, merged