feat(readme): add README.md & fix indent test
FOLHOMEE/mongoose-tracker pull request #2
Opened 2022-01-27 17:09 UTC by barder60

2022-01-27 19:55 UTC, milanito requested changes
Pas mal de retour

2022-01-27 19:55 UTC, milanito commented on README.md
> +Rewrite from deprecated [mongoose-trackable](https://www.npmjs.com/package/mongoose-trackable)
```suggestion
Rewrite from old [mongoose-trackable](https://www.npmjs.com/package/mongoose-trackable) which has not been updated for 7 years
```

2022-01-27 19:55 UTC, milanito commented on README.md
> +
Manque la partie `yarn`

2022-01-27 19:55 UTC, milanito commented on README.md
> +
```suggestion
## Contributing

- Use eslint to lint your code.
- Add tests for any new or changed functionality.
- Update the readme with an example if you add or change any functionality.

## Legal

Author: [Folhomee](https://www.folhomee.fr/). License Apache-2.0
```

Ca fait un backlink ahahaha

2022-01-27 19:55 UTC, milanito commented on README.md
> +## History
Saute une ligne c'est du markdown

2022-01-27 19:55 UTC, milanito commented on README.md
> +---------------
pas besoin si tu met `##`

```suggestion
```

2022-01-27 19:55 UTC, milanito commented on README.md
> +---------------
```suggestion
```

2022-01-27 19:55 UTC, milanito commented on README.md
> +---------------
```suggestion
```

2022-01-27 19:55 UTC, milanito commented on README.md
> +---------------
```suggestion
```

2022-01-27 19:56 UTC, milanito commented
@barder60 regarde le preview du document https://github.com/FOLHOMEE/mongoose-tracker/blob/4bc5519d0d6182f5f53b2b922217344e7d5409e7/README.md avant c'est important

2022-01-28 08:28 UTC, barder60 commented on README.md
> +Rewrite from deprecated [mongoose-trackable](https://www.npmjs.com/package/mongoose-trackable)
:+1:

2022-01-28 08:28 UTC, barder60 commented on README.md
> +
:+1:

2022-01-28 08:28 UTC, barder60 commented on README.md
> +
:+1:

2022-01-28 08:28 UTC, barder60 commented on README.md
> +## History
:+1:

2022-01-28 13:31 UTC, milanito approved these changes
@barder60 oublie pas les modif dans le package.json

2022-01-31 08:27 UTC, merged